accounts/serializers.py, accounts/urls.py, accounts/views.py, instytution_backend/settings.py, instytution_backend/urls.py, utils/utils.py
#7 created UserSignUpView, UserOTPVerifyView, SignInUserView
succussfully created user signup verifyotp and sign views
=> #7 created UserSignUpView, UserOTPVerifyView, SignInUserView

accounts/urls.py, accounts/views.py, instytution_backend/settings.py, requirements.txt
#10 Completed Resent OTP added Redis cache updated requirement text
=> #10 Completed Resent OTP added Redis cache updated requirement text

accounts/serializers.py
#10v1 updated otp error message by aashi
=> #10v1 updated otp error message by aashi

accounts/manager.py, accounts/models.py, accounts/permissions.py, accounts/serializers.py, accounts/urls.py, accounts/views.py
#14 created SubAdminCreateView by Aashi
updated user serializer with removing fields all to required fields 
updated blocked user from sign in 
created sub admin create view
=> #14 created SubAdminCreateView by Aashi

accounts/urls.py
=> #21 refresh token api added to accounts/urls.py

courses/serializers.py, courses/urls.py, courses/views.py, instytution_backend/urls.py
=> #33 created API for retrieving all programs. by Anaz

courses/serializers.py, courses/urls.py, courses/views.py
=> #38 API created fetching courses data of a specific program passed in the url. by Anaz

accounts/models.py, custom_admin/pagination.py, custom_admin/urls.py, custom_admin/views.py
54 created role based user listing api with serach and pagination
=> #54 created role based user listing api with serach and pagination

courses/serializers.py, courses/urls.py, courses/views.py
=> created crud on programs 

courses/urls.py, courses/views.py
=> #69v1 updated program creation

course_admin/serializers.py, course_admin/urls.py, course_admin/views.py, courses/serializers.py, courses/urls.py, courses/views.py
#69v2 updated program api ( name instead of id)
=> #69v2 updated program api ( name instead of id)

custom_admin/urls.py, custom_admin/views.py
Added  instructore list and unblock api by saeed
=> #84 after added instructore list and unblock api by saeed

courses/models.py
=> Set Video Cloudinary field

courses/serializers.py, courses/urls.py, courses/views.py
#97 created api for listing instructors without permissions
=> #97 created api for listing instructors without permissions

.vscode/settings.json, custom_admin/pagination.py
updated pagination number by saeed nm
=> #99 updated pagination number by saeed nm

course_admin/serializers.py
#83v2 added instructor_id field in batch serializer
=> #83v2 added instructor_id field in batch serializer   

requirements.txt
#108v1 addded requiremtn txt file by saeeed
=> #108v1 addded requiremtn txt file by saeeed

accounts/models.py, accounts/serializers.py, accounts/urls.py, accounts/views.py, courses/models.py
created cart apis and updated wishlit modal
=> #122v1 created cart apis by saeed nm

class_room/serializers.py, class_room/urls.py, class_room/views.py
=> Created Session VIdeo apis

order/serializers.py
=> payment error fixed by saeed

course_admin/serializers.py, course_admin/urls.py, course_admin/views.py
#192 course admin purchase report api completed
=> #192 course admin purchase report api completed

course_admin/serializers.py, course_admin/views.py, shop_admin/urls.py, shop_admin/views.py
#194 created purchaseReport api for store
=> #194 created purchaseReport api for store
